# NDAIVI Configuration

# Language configuration
languages:
  # English is always the default source language
  source: "en"
  
  # Target languages to translate into
  # Format: "language_code": "language_name"
  targets:
    "es": "Spanish"
    # Add or remove languages as needed
    # Use ISO 639-1 two-letter language codes
  
  # Number of categories to translate in one batch
  translation_batch_size: 50

# Translation configuration
translation:
  enabled: true
  default_source_lang: "en"
  default_target_lang: "es"
  batch_size: 50
  cache_enabled: true
  cache_ttl: 86400  # 24 hours

# Claude analyzer configuration
claude_analyzer:
  api_key: "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"
  api_base_url: "https://api.anthropic.com/v1/messages"
  claude_model: "claude-3-5-haiku-20241022"
  enable_cache: true
  cache_ttl: 86400
  cache_dir: ".cache"
  max_tokens: 4000
  temperature: 0.0
  min_confidence_threshold: 0.7

# Keywords for filtering
keywords:
  positive:
    - "manufacturer"
    - "brand"
    - "companies"
    - "products"
    - "category"
    - "catalog"
    - "brands"
  negative:
    - "cart"
    - "checkout"
    - "login"
    - "register"
    - "account"
    - "privacy"
    - "terms"

# Prompt templates for Claude AI
prompt_templates:
  # System prompts
  system:
    manufacturer: "You are a specialized AI that analyzes web content to identify manufacturers and their product categories."
    page_type: "You are a specialized AI that classifies pages as: brand pages, brand category pages, or other pages."
    translation: "You are a specialized AI that translates product categories while preserving manufacturer names."
    general: "You are an AI specialized in extracting structured information about manufacturers and their product categories from web content."

  # Page analysis prompts
  page_type_analysis: |
    Analyze this content and determine if it's:
    1. A brand/manufacturer page (contains multiple product categories)
    2. A brand category page (specific product category within a brand)
    3. Other (not related to manufacturers or product categories)

    Respond in JSON format:
    {
      "page_type": "brand_page|brand_category_page|other",
      "confidence": 0.0-1.0,
      "reasoning": "Brief explanation of your classification"
    }

  # Manufacturer extraction prompts
  extract_manufacturer: |
    Extract the manufacturer/brand name from this page.
    
    Respond in JSON format:
    {
      "manufacturer_name": "Name of the manufacturer",
      "confidence": 0.0-1.0
    }

  # Category extraction prompts
  extract_categories: |
    Extract all product categories for this manufacturer.
    Only include categories that are clearly associated with this manufacturer.
    
    Respond in JSON format:
    {
      "categories": [
        "Category 1",
        "Category 2",
        ...
      ]
    }

  # Translation prompts
  translate_categories: |
    Translate the following product categories from {source_language} to {target_language}.
    Preserve any brand names or proper nouns without translation.
    
    Categories:
    {categories}
    
    Respond in JSON format:
    {
      "translations": [
        "Translated Category 1",
        "Translated Category 2",
        ...
      ]
    }

# Web crawler configuration
web_crawler:
  # Target website - used as the default start URL if none is specified
  target_website: "manualslib.com"
  
  # Crawler behavior
  max_depth: 3
  max_urls: null  # null means no limit (for production), set a number for testing
  max_urls_per_domain: 100
  max_concurrent_requests: 5
  request_delay: 1.0
  timeout: 30
  user_agent: 'Mozilla/5.0 (compatible; NDaiviBot/1.0; +https://ndaivi.com/bot)'
  respect_robots_txt: true
  follow_redirects: true
  
  # Domain restrictions
  allowed_domains: [manualslib.com]
  disallowed_domains: []
  allowed_url_patterns: []
  disallowed_url_patterns: []
  
  # Content handling
  max_content_size: 5242880  # 5MB
  extract_metadata: true
  extract_links: true
  extract_text: true
  
  # Database and state
  db_path: 'scraper/data/crawler.db'
  
  # Crawl mode
  restrict_to_start_domain: false
  single_domain_mode: true
  
  # Stats
  stats_update_interval: 10  # Update stats every 10 URLs
  verbose_logging: false  # Set to true for detailed debug logs
  
  # URL queue management
  max_unanalyzed_urls: 1024   # Maximum number of non-analyzed URLs before slowing down crawler
  crawl_speed_check_interval: 5   # Check non-analyzed URL count every 5 seconds

# Redis configuration
redis:
  host: 'localhost'
  port: 6379
  db: 0
  password: null
  socket_timeout: 5
  socket_connect_timeout: 5
  retry_on_timeout: true
  health_check_interval: 30

# Application configuration
application:
  # Component settings
  components:
    crawler:
      enabled: true
      worker_threads: 1
      auto_start: false  # Don't start crawler automatically
      resume_from_db: true  # Resume from database state
    analyzer:
      enabled: true
      worker_threads: 1
      batch_size: 10
    stats:
      enabled: true
      update_interval: 5  # Update stats every 5 seconds
  
  # Redis channels - Single source of truth for all channel names
  channels:
    # Crawler channels
    crawler_commands: 'ndaivi:crawler:commands'
    crawler_status: 'ndaivi:crawler:status'
    
    # Analyzer channels
    analyzer_commands: 'ndaivi:analyzer:commands'
    analyzer_status: 'ndaivi:analyzer:status'
    
    # Additional channels for container app
    backlog_status: 'ndaivi:backlog:status'
    backlog_request: 'ndaivi:backlog:request'
    container_status: 'ndaivi:container:status'
    analyzer_results: 'ndaivi:analyzer:results'
    stats: 'ndaivi:stats'
    system: 'ndaivi:system'

# PostgreSQL database configuration
database:
  host: 'localhost'
  port: 5432
  user: 'postgres'
  password: 'postgres'
  dbname: 'ndaivi'
  sslmode: 'disable'
