# Competitor Scraping Engine Configuration

# Language configuration
languages:
  # English is always the default source language
  source: "en"
  
  # Target languages to translate into
  # Format: "language_code": "language_name"
  targets:
    "es": "Spanish"
    # Add or remove languages as needed
    # Use ISO 639-1 two-letter language codes
    # Examples:
    # "ja": "Japanese"
    # "ko": "Korean"
    # "zh": "Chinese"
    # "ru": "Russian"
  
  # Number of categories to translate in one batch
  translation_batch_size: 50

# Target website to crawl
target_url: "https://www.manualslib.com"

# Database configuration
database:
  path: "database/manuals.db"
  
# Scheduling and execution configuration
scheduling:
  # Time allocation between scraper and manufacturer website finder (0-100)
  # Higher values allocate more time to competitor scraper
  # Lower values allocate more time to manufacturer website finder
  time_allocation: 70
  
  # Maximum runtime in minutes (0 means no time limit)
  max_runtime_minutes: 0
  
  # Checkpoint interval in minutes (save state for resuming)
  checkpoint_interval: 5
  
  # Background processing configuration
  background:
    # Enable background processing
    enabled: false
    
    # Process ID file to track background processes
    pid_file: "logs/ndaivi_process.pid"
    
    # Status file to track progress
    status_file: "logs/ndaivi_status.json"

# AI APIs configuration
ai_apis:
  anthropic:
    api_key: "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"
    model: "claude-3-haiku-20240307"
    sonnet_model: "claude-3-7-sonnet-20250219"

# Claude analyzer configuration
claude_analyzer:
  api_key: "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"
  api_base_url: "https://api.anthropic.com/v1/messages"
  model: "claude-3-opus-20240229"
  enable_cache: true
  cache_ttl: 86400
  cache_expiration_days: 7
  max_tokens: 4000
  temperature: 0.1
  min_confidence_threshold: 0.7

# Crawling settings
crawling:
  max_depth: 3
  delay_between_requests: 1.0
  max_pages_per_run: 0  # 0 means no limit, will crawl until no pages remain
  build_sitemap: true  # Enable sitemap building
  respect_robots_txt: false  # Temporarily disable robots.txt to test scraper
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  request_timeout: 10
  max_urls_per_domain: 100
  domain_validation_mode: "strict"
  seed_urls:
    - "https://www.manualslib.com"
  initial_urls:
    - "https://www.manualslib.com"
  max_retries: 3
  retry_delay: 5
  follow_external_links: false

# URL priority settings
url_priority:
  # Base priority values (lower is higher priority)
  seed_url_priority: 10
  manufacturer_page_priority: 20
  category_page_priority: 30
  product_page_priority: 40
  default_priority: 100
  # Priority modifiers
  depth_modifier: 5  # Priority decreases by this amount per depth level
  query_params_modifier: 10  # URLs with query parameters get lower priority
  keyword_match_bonus: -15  # Priority bonus for URLs with keyword matches

# Content extraction settings
content_extraction:
  # Maximum content length to extract (in characters)
  max_content_length: 50000
  # HTML elements to prioritize for extraction
  priority_elements:
    - "h1"
    - "h2"
    - "h3"
    - "title"
    - "meta[name='description']"
    - "meta[property='og:title']"
    - "meta[property='og:description']"
  # Elements to exclude from extraction
  exclude_elements:
    - "script"
    - "style"
    - "footer"
    - "nav"
    - "aside"
  # Maximum links to extract per page
  max_links_per_page: 100

# Keywords for filtering
keywords:
  positive:
    - "manufacturer"
    - "brand"
    - "companies"
    - "products"
    - "category"
    - "catalog"
    - "brands"
  negative:
    - "cart"
    - "checkout"
    - "login"
    - "register"
    - "account"
    - "privacy"
    - "terms"

# Scraper configuration
scraper:
  # Maximum number of pages to process in a single batch
  batch_size: 100
  
  # Timeout in seconds for page requests
  request_timeout: 30
  
  # Number of retries for failed requests
  max_retries: 3
  
  # Delay between retries in seconds
  retry_delay: 5
  
  # Seed URLs for the scraper
  seed_urls:
    - "https://www.manualslib.com/"
  
# Manufacturer website finder configuration
manufacturer_finder:
  # Maximum number of manufacturers to process in a single batch
  batch_size: 20
  
  # Maximum number of search results to validate per manufacturer
  max_search_results: 3
  
  # Timeout in seconds for website validation
  validation_timeout: 45
  
  # Delay between manufacturer processing in seconds
  processing_delay: 3

# Prompt templates for Claude AI
prompt_templates:
  # System prompts
  system:
    manufacturer: "You are a specialized AI that analyzes web content to identify manufacturers and their product categories."
    page_type: "You are a specialized AI that classifies pages as: brand pages, brand category pages, or other pages."
    translation: "You are a specialized AI that translates product categories while preserving manufacturer names."
    general: "You are an AI specialized in extracting structured information about manufacturers and their product categories from web content."

  # Page analysis prompts
  page_type_analysis: |
    Analyze this content and determine if it's:
    1. A brand/manufacturer page (contains multiple product categories)
    2. A brand category page (specific product category within a brand)
    3. Inconclusive (not enough information to make a determination)
    4. Other (not related to product categories)

    Content:
    {content}

    Rules:
    - ONLY respond with one of: "brand_page", "brand_category_page", "inconclusive", or "other"
    - "brand_page" = Main manufacturer page listing multiple product categories
    - "brand_category_page" = Page for a specific product category within a brand
    - "inconclusive" = Not enough information to determine the page type
    - "other" = Any other type of page (about, contact, etc.)
    - Use "inconclusive" when you need more context to make a determination
    - Use "other" when you are confident it's not brand-related

  # Extraction prompts
  brand_page_extraction: |
    Extract manufacturer name and product categories from this brand page.

    Content:
    {content}

    Rules:
    1. ONLY extract categories that are clearly product lines or model types
    2. IGNORE:
       - Individual product names/models
       - Support/service categories
       - Accessory categories
    3. Format: Exactly as shown below, nothing else

    # RESPONSE_START
    MANUFACTURER: [name]
    CATEGORIES:
    - [category 1]
    - [category 2]
    WEBSITE: [official website if found]
    # RESPONSE_END

  category_page_extraction: |
    Extract manufacturer name and product category from this category page.

    Content:
    {content}

    Rules:
    1. ONLY extract the main category name
    2. IGNORE subcategories and individual products
    3. Format: Exactly as shown below, nothing else

    # RESPONSE_START
    MANUFACTURER: [name]
    CATEGORY: [category name]
    WEBSITE: [official website if found]
    # RESPONSE_END

  # Keyword filtering
  keyword_filter:
    positive:
      - manufacturer
      - brand
      - company
      - product
      - category
      - catalog
      - portfolio
      - series
      - model
      - range
      - lineup
    negative:
      - login
      - register
      - cart
      - checkout
      - account
      - privacy
      - terms
      - contact
      - about us
      - faq
      - support

  # Translation prompt
  translation_batch: |
    Translate these product categories to {target_language}. 
    Manufacturer name: {manufacturer_name}

    Categories:
    {categories}

    Rules:
    1. Keep "{manufacturer_name}" untranslated
    2. Format each line: "[Original] → [Translation]"
    3. Preserve technical terms and model numbers
    4. Use industry-standard translations
